# Specify the version of the Docker Compose.
version: "3.9"

# Define the services and applications that make up PeerPrep G52.
services:
  frontend:
    build: ./frontend # Path to the directory containing the Dockerfile for building the frontend image.
    ports:
      - 3000:3000 # Maps port 3000 on the host to port 3000 in the container, making the app accessible on the host.
    env_file:
      - ./frontend/.env
    # volumes: # Not necessarily needed for now
    # networks: # Not necessarily needed for now
     
  user-service:
    build: ./backend/user-service # Path to the directory containing the Dockerfile for building the backend/user-service image.
    ports:
      - 3001:3001 # Maps port 4000 on the host to port 4000 in the container, making the app accessible on the host.
    env_file:
      - ./backend/user-service/.env
    # volumes: # Not necessarily needed for now
    # networks: # Not necessarily needed for now

  question-service:
    build: ./backend/question-service # Path to the directory containing the Dockerfile for building the backend/question-service image.
    ports:
      - 8000:8000 # Maps port 4000 on the host to port 4000 in the container, making the app accessible on the host.
    env_file:
      - ./backend/question-service/.env
    # volumes: # Not necessarily needed for now
    # networks: # Not necessarily needed for now